

//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"
#include "Views\PhotoCapture.xaml.h"




void ::Catch::PhotoCapture::InitializeComponent()
{
    if (_contentLoaded)
        return;

    _contentLoaded = true;

    // Call LoadComponent on ms-appx:///Views/PhotoCapture.xaml
    ::Windows::UI::Xaml::Application::LoadComponent(this, ref new ::Windows::Foundation::Uri(L"ms-appx:///Views/PhotoCapture.xaml"), ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);

    // Get the Storyboard named 'AutoFocusInProgress'
    AutoFocusInProgress = safe_cast<::Windows::UI::Xaml::Media::Animation::Storyboard^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"AutoFocusInProgress"));
    // Get the Storyboard named 'AutoFocusLocked'
    AutoFocusLocked = safe_cast<::Windows::UI::Xaml::Media::Animation::Storyboard^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"AutoFocusLocked"));
    // Get the CaptureElement named 'previewElement'
    previewElement = safe_cast<::Windows::UI::Xaml::Controls::CaptureElement^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"previewElement"));
    // Get the Grid named 'AutoFocusBrackets'
    AutoFocusBrackets = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"AutoFocusBrackets"));
    // Get the TextBlock named 'captureNum'
    captureNum = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"captureNum"));
}

void ::Catch::PhotoCapture::Connect(int connectionId, Platform::Object^ target)
{
    switch (connectionId)
    {
    case 1:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Catch::PhotoCapture::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&PhotoCapture::CaptureButton_Click);
        break;
    case 2:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Catch::PhotoCapture::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&PhotoCapture::AcceptBtn_Click);
        break;
    }
    (void)connectionId; // Unused parameter
    (void)target; // Unused parameter
    _contentLoaded = true;
}

